#!/usr/bin/env python
import csv
import sys

HPO_FILE = '../onto/data/hpo_phenotypes.tsv'
hpo_id_to_name = {}
with open(HPO_FILE) as f:
  for line in f:
    toks = line.strip().split('\t')
    hpo_id = toks[0]
    hpo_name = toks[1]
    hpo_id_to_name[hpo_id] = hpo_name


input_csv = sys.argv[1]

def create_row_id(row):
  row_id = ''
  row_id += row[0]
  row_id += '_'
  row_id += row[1]
  row_id += '_'
  row_id += row[2]
  row_id += '_'
  row_id += row[3]
  row_id += '_'
  row_id += row[4]
  row_id += '_'
  row_id += '|'.join(row[5])
  row_id += '_'
  row_id += '|'.join(row[6])
  return row_id

writer = csv.writer(sys.stdout)
with open(input_csv) as f:
  reader = csv.reader(f)
  for i, row in enumerate(reader):
    if i == 0:
      new_row = ['row_id'] + row + ['hpo_name']
    else:
      hpo_id = row[4]
      row[7] = row[7].replace('-LRB-', '(')
      row[7] = row[7].replace('-RRB-', ')')
      row[7] = row[7].replace('-LSB-', '[')
      row[7] = row[7].replace('-RSB-', ']')
      row_id = create_row_id(row)
      if hpo_id in hpo_id_to_name:
        new_row = [row_id] + row + [hpo_id_to_name[hpo_id]]
      else:
        new_row = [row_id] + row + ['Unknown_HPO_Id']
    writer.writerow(new_row)
