#!/usr/bin/env python
import csv
import sys

input_csv = sys.argv[1]

writer = csv.writer(sys.stdout)
with open(input_csv) as f:
  reader = csv.reader(f)
  for i, row in enumerate(reader):
    if i == 0:
      new_row = ['row_id'] + row
    else:
      row[4] = row[4].replace('-LRB-', '(')
      row[4] = row[4].replace('-RRB-', ')')
      row[4] = row[4].replace('-LSB-', '[')
      row[4] = row[4].replace('-RSB-', ']')
      row_id = row[-1]
      new_row = [row_id] + row
    writer.writerow(new_row)
