#!/usr/bin/env python
import csv
import sys

input_csv = sys.argv[1]

writer = csv.writer(sys.stdout)
with open(input_csv) as f:
  reader = csv.reader(f)
  for i, row in enumerate(reader):
    if i == 0:
      new_row = ['row_id'] + row
    else:
      hpo_id = row[4]
      row[7] = row[7].replace('-LRB-', '(')
      row[7] = row[7].replace('-RRB-', ')')
      row[7] = row[7].replace('-LSB-', '[')
      row[7] = row[7].replace('-RSB-', ']')
      row_id = row[-2]+'_'+row[-1] #GeneMentionID_PhenoMentionID
      new_row = [row_id] + row
    writer.writerow(new_row)
