#!/usr/bin/env python
import csv
import sys

HPO_FILE = '../onto/data/hpo_phenotypes.tsv'
hpo_id_to_name = {}
with open(HPO_FILE) as f:
  for line in f:
    toks = line.strip().split('\t')
    hpo_id = toks[0]
    hpo_name = toks[1]
    hpo_id_to_name[hpo_id] = hpo_name


input_csv = sys.argv[1]

writer = csv.writer(sys.stdout)
with open(input_csv) as f:
  reader = csv.reader(f)
  for i, row in enumerate(reader):
    if i == 0:
      new_row = row + ['hpo_name']
    else:
      hpo_id = row[6]
      row[9] = row[9].replace('-LRB- ', '(')
      row[9] = row[9].replace(' -RRB-', ')')
      row[9] = row[9].replace('-LSB- ', '[')
      row[9] = row[9].replace(' -RSB-', ']')
      row[9] = row[9].replace('-LRB-', '(')
      row[9] = row[9].replace('-RRB-', ')')
      row[9] = row[9].replace('-LSB-', '[')
      row[9] = row[9].replace('-RSB-', ']')
      if hpo_id in hpo_id_to_name:
        new_row = row + [hpo_id_to_name[hpo_id]]
      else:
        new_row = row + ['Unknown_HPO_Id']
    writer.writerow(new_row)
