#!/usr/bin/env python
import csv
import sys

HPO_FILE = '../onto/data/hpo_phenotypes.tsv'
hpo_id_to_name = {}
with open(HPO_FILE) as f:
  for line in f:
    toks = line.strip().split('\t')
    hpo_id = toks[0]
    hpo_name = toks[1]
    hpo_id_to_name[hpo_id] = hpo_name


input_csv = sys.argv[1]

writer = csv.writer(sys.stdout)
with open(input_csv) as f:
  reader = csv.reader(f)
  for i, row in enumerate(reader):
    if i == 0:
      new_row = row + ['hpo_name']
    else:
      hpo_id = row[4]
      new_row = row + [hpo_id_to_name[hpo_id]]
    writer.writerow(new_row)
