#!/usr/bin/env python
import csv
import sys

input_csv = sys.argv[1]

writer = csv.writer(sys.stdout)
with open(input_csv) as f:
  reader = csv.reader(f)
  for i, row in enumerate(reader):
    if i == 0:
      new_row = ['row_id'] + row + ['hpo_name']
    else:
      hpo_id = row[4]
      row[5] = row[5].replace('-LRB-', '(')
      row[5] = row[5].replace('-RRB-', ')')
      row[5] = row[5].replace('-LSB-', '[')
      row[5] = row[5].replace('-RSB-', ']')
      row_id = row[-1]
      new_row = [row_id] + row + [row[-2]]
    writer.writerow(new_row)
